version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network
  mysql-db:
    container_name: mysql-db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_cadastro
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network
  api-cadastro-usuario:
    container_name: api-cadastro-usuario
    build:
      context: .
      dockerfile: Dockerfile
    image: api-cadastro-usuario:latest
    environment:
      MYSQL_DATABASE: mysql_cadastro
      MYSQL_URL: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
