name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
        
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v3.3.1
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            erikkater/spring-boot-api-cadastro:v1
            erikkater/spring-boot-api-cadastro:latest
