name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - name: construção da imagem docker
      - uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: Dockerfile
          push: true
          tags:  |
            erikxavier/live-spring-boot-api-cadastro:v1
            erikxavier/live-spring-boot-api-cadastro:latest
            
