name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3

      - name: autenticador no docker hub
        uses: docker/login-action@v2.2.0
        with: 
          username:${{secrets.DOCKERHUB_USER}}
          password:${{secrets.DOCKERHUB_PWD}}
        
      
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: Dockerfile
          push: true
          tags:  |
            erikxavier/live-spring-boot-api-cadastro:v1
            erikxavier/live-spring-boot-api-cadastro:latest
